routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'BookController@index')->name('books');
Route::resource('books', 'BookController');
Route::post('/Give_book', 'BookController@Give_book')->name('Give_book');
Route::post('/return_book', 'BookController@Return_book')->name('return_book');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'name', 'author', 'categorie_id',
    ];

    public function Categorie()
    {
        return $this->belongsTo('App\Categorie');
    }

    public function User()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }
}

app/Categorie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    public function Books()
    {
        return $this->hasMany('App\Book');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function Books()
    {
        return $this->hasMany('App\Book');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\User;
use App\Categorie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::get();
        $books = Book::get();
        return view('book.index', compact('books', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categorie::get();
        return view('book.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      try{
          $result = DB::transaction(function() use ($request){

              $book = new Book;

              $book->fill([
                  'name' => $request->name,
                  'author' => $request->author,
                  'categorie_id' => $request->category,
              ]);

              $book->save();

              DB::commit();


          });

          return redirect()->route('books');
      } catch (Exception $e){
          DB::rollBack();
          return redirect()->route('books');
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(book $book)
    {
        return view('book.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id);
        $categories = Categorie::get();
        return view('book.edit', compact('categories', 'book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      try{
          $result = DB::transaction(function() use ($request, $id){

              $book = Book::find($id);

              $book->fill([
                  'name' => $request->name,
                  'author' => $request->author,
                  'categorie_id' => $request->category,
              ]);

              $book->save();

              DB::commit();


          });

          return redirect()->route('books');
      } catch (Exception $e){
          DB::rollBack();
          return redirect()->route('books');
      }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Book::find($id)->delete();
        return json_encode(["status" => "delete"]);
    }

    public function Give_book(Request $request){
      try{
          $result = DB::transaction(function() use ($request){

              $book = Book::find($request->idbook);
              $book->status = 0;
              $book->user_id = $request->user;
              $book->save();
              DB::commit();


          });
          return redirect()->route('books');
      } catch (Exception $e){
          DB::rollBack();
          return redirect()->route('books');
      }
    }

    public function Return_book(Request $request){
      try{
          $result = DB::transaction(function() use ($request){

              $book = Book::find($request->idbook2);
              $book->status = 1;
              $book->user_id = null;
              $book->save();
              DB::commit();

          });

          return redirect()->route('books');
      } catch (Exception $e){
          DB::rollBack();
          return redirect()->route('books');
      }
    }
}

app/Http/Controllers/CategorieController.php
<?php

namespace App\Http\Controllers;

use App\categorie;
use Illuminate\Http\Request;

class CategorieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function show(categorie $categorie)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function edit(categorie $categorie)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, categorie $categorie)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function destroy(categorie $categorie)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/book/create.blade.php
@extends('layouts.primary')

@section('content')
<div class="container-fluid">
  <div class="row page-titles">
      <div class="col-12 align-self-center">
          <h4 class="text-themecolor">Add book</h4>

      </div>
  </div>
  <div class="row">
      <div class="col-12">
          <div class="card">
              <div class="card-body">
                  <h5>Información</h5>
                  <form action="{{route('books.store')}}" method="post" accept-charset="UTF-8">
                    <input name="_token" type="hidden" value="{{ csrf_token() }}"/>
                    <div class="row">

                        <div class="col-12 col-sm-4">
                              <div class="form-group">
                                  <label for="">Name<span class="requerido">*</span></label>
                                  <input type="text" class="form-control" id="name" name="name" placeholder="" required>
                              </div>
                        </div>
                        <div class="col-12 col-sm-4">
                              <div class="form-group">
                                  <label for="">Author<span class="requerido">*</span></label>
                                  <input type="text" class="form-control" id="author" name="author" placeholder="" required>
                              </div>
                        </div>

                        <div class="col-12 col-sm-4">
                              <div class="form-group">
                                  <label for="">Category</label>
                                  <select class="form-control"  name="category" required>
                                    <option value="">Seleccionar...</option>
                                    @foreach ($categories as $categorie)
                                      <option value="{{$categorie->id}}">{{$categorie->name}}</option>
                                    @endforeach

                                  </select>
                              </div>
                        </div>
                    </div>
                    <div class="col-12 text-center mt-5 mb-4">
                        <input type="submit"class="btn btn-info" value="Add book">
                    </div>
                  </form>

              </div>
          </div>
      </div>
  </div>

</div>
@endsection
@section('modal')

@endsection
@section('script')

@endsection

resources/views/book/edit.blade.php
@extends('layouts.primary')

@section('content')
<div class="container-fluid">
  <div class="row page-titles">
      <div class="col-12 align-self-center">
          <h4 class="text-themecolor">Add book</h4>

      </div>
  </div>
  <div class="row">
      <div class="col-12">
          <div class="card">
              <div class="card-body">
                  <h5>Información</h5>
                  <form action="{{route('books.update', $book->id)}}" method="POST" accept-charset="UTF-8">
                    <input type="hidden" name="_method" value="PUT">
                     <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="row">

                        <div class="col-12 col-sm-4">
                              <div class="form-group">
                                  <label for="">Name<span class="requerido">*</span></label>
                                  <input type="text" class="form-control" id="name" name="name" value="{{$book->name}}" required>
                              </div>
                        </div>
                        <div class="col-12 col-sm-4">
                              <div class="form-group">
                                  <label for="">Author<span class="requerido">*</span></label>
                                  <input type="text" class="form-control" id="author" name="author" value="{{$book->author}}" required>
                              </div>
                        </div>

                        <div class="col-12 col-sm-4">
                              <div class="form-group">
                                  <label for="">Category</label>
                                  <select class="form-control"  name="category" required>

                                    @foreach ($categories as $categorie)
                                      @if ($book->categorie_id == $categorie->id)
                                        <option value="{{$categorie->id}}" selected>{{$categorie->name}}</option>
                                      @else
                                        <option value="{{$categorie->id}}">{{$categorie->name}}</option>
                                      @endif

                                    @endforeach

                                  </select>
                              </div>
                        </div>
                    </div>
                    <div class="col-12 text-center mt-5 mb-4">
                        <input type="submit"class="btn btn-info" value="to update">
                    </div>
                  </form>

              </div>
          </div>
      </div>
  </div>

</div>
@endsection
@section('modal')

@endsection
@section('script')

@endsection

resources/views/book/index.blade.php
@extends('layouts.primary')

@section('content')

    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-8 align-self-center">
                <h4 class="text-themecolor">List of books</h4>

            </div>

        </div>
    </div>
<hr>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="table-responsive">
          <table id="example" class="table table-striped table-bordered" style="width:100%">
              <thead>
                  <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Author</th>
                      <th>Category</th>
                      <th>Status</th>
                      <th>Options</th>
                      <th>Published date</th>
                  </tr>
              </thead>
              <tbody>
                @foreach ($books as $book)
                  <tr>
                    <td>{{$book->id}}</td>
                    <td>
                      <div class="media">
                        <img class="mr-3" src="/assets/img/i-gde.png" width="34" alt="Producto 1">
                        <div class="media-body">
                          {{$book->name}}
                        </div>
                      </div>
                    </td>
                    <td>{{$book->author}}</td>
                    <td>{{$book->categorie->name}}</td>
                    <td>
                      @if ($book->status == 1)
                        <span class="text-success">is available </span>
                      @else
                        <span class="text-danger">Not available </span>
                      @endif
                    </td>
                    <td>
                      <div class="d-flex justify-content-between align-items-center">
                        @if ($book->status == 1)
                          <a href="#" onclick="Give_book({{$book->id}},'{{$book->name}}')" data-toggle="modal" data-target="#mNuevoProyecto" class="acccion btn btn-link btn-sm d-lg-block m-l-15"><i class="fa fa-book"></i> <span>Give a book</span></a>
                        @elseif ($book->user_id != null)
                          <a href="#" onclick="See_user({{$book->id}},'{{$book->User->name}}')" data-toggle="modal" data-target="#user_book" class="acccion btn btn-link btn-sm d-lg-block m-l-15"><i class="fa fa-book"></i> <span>Who has the book?</span></a>
                        @endif
                        <a href="{{route('books.edit', $book->id)}}" class="acccion btn btn-link btn-sm d-lg-block m-l-15"><i class="fa fa-pencil"></i> <span>Edit book</span></a>

                        <a href="#" onclick="Delete_book({{$book->id}})" class="acccion btn btn-link btn-sm d-lg-block m-l-15"><i class="fa fa-trash-o"></i> <span>Delete</span></a>
                      </div>
                    </td>
                    <td>{{$book->created_at}}</td>
                  </tr>
                @endforeach

              </tbody>
          </table>
      </div>
    </div>
  </div>
</div>
@endsection
@section('modal')
  <div class="modal fade" id="mNuevoProyecto" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Give a book </h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                <form action="{{route('Give_book')}}" method="POST" accept-charset="UTF-8">
                   <input type="hidden" name="_token" value="{{ csrf_token() }}">
                      <div class="form-group">
                          <label for="proyectoNombre">Book name<span class="requerido">*</span></label>
                          <input type="text" class="form-control" name="namebook" id="namebook" disabled>
                          <input type="hidden" name="idbook" id="idbook" >

                          <label for="cliente">Users</label>
                          <select class="form-control" name="user" required>
                            <option value="">Select...</option>
                            @foreach ($users as $user)
                              <option value="{{$user->id}}">{{$user->name}}</option>
                            @endforeach

                          </select>
                          <div class="text-right mt-2">
                            <input type="submit" class="btn btn-primary btn-sm" value="Give book">
                          </div>
                      </div>

                  </form>
              </div>
          </div>
      </div>
  </div>
  <div class="modal fade" id="user_book" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Who has the book?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                <form action="{{route('return_book')}}" method="POST" accept-charset="UTF-8">
                   <input type="hidden" name="_token" value="{{ csrf_token() }}">

                      <div class="form-group">
                          <label for="proyectoNombre">User name<span class="requerido">*</span></label>
                          <input type="text" class="form-control" name="nameuser" id="nameuser" disabled>
                          <input type="hidden" name="idbook2" id="idbook2" >

                      </div>
                      <div class="text-right mt-2">
                        <input type="submit" class="btn btn-primary btn-sm" value="Return book">
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
@endsection
@section('script')
  <script>
    function See_user(idbook, name){
      $('#nameuser').val(name);
      $('#idbook2').val(idbook);
    }
    function Give_book(idbook, name){
      $('#namebook').val(name);
      $('#idbook').val(idbook);
    }
    function Delete_book(id){

        Swal.fire({
         title: 'Are you sure?',
         text: "You won't be able to revert this!",
         type: 'warning',
         showCancelButton: true,
         confirmButtonColor: '#3085d6',
         cancelButtonColor: '#d33',
         confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
         if (result.value) {
           $.ajax({
               url:  '/books/'+id,
               headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
               type: "DELETE",
               async: true,
               beforeSend: function() {
                   $(".loading").toggle();
               },success:  function (data) {
                 dat = JSON.parse(data);
                 console.log(dat.status);
                  if (dat.status == 'delete') {
                    Swal.fire(
                      'Deleted!',
                      'Your book has been deleted.',
                      'success'
                    )
                    window.location.href = "{{route('books')}}";
                  }
               }
           });


         }
        })

    }
      $(document).ready(function() {
          $('#example').DataTable({
              "language": {
                  "search": "Buscar",
                  "info":           "Mostrando _START_ - _END_ de _TOTAL_ libros",
                  "infoEmpty":      "Mostrando 0 de 0 de 0 entradas",
                  "lengthMenu":     "Mostrando _MENU_ registros",
                  "paginate": {
                      "first":      "Primero",
                      "last":       "Último",
                      "next":       "Siguiente",
                      "previous":   "Anterior"
                  },
              }
          });
      } );
  </script>
@endsection

resources/views/book/show.blade.php
@extends('layouts.primary')

@section('content')
    <h1>create</h1>
@endsection
@section('modal')

@endsection
@section('script')

@endsection

resources/views/layouts/primary.blade.php
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<title>The Library</title>
	<script src="/js/app.js"></script>

	<!-- Favicon icon -->
    <link rel="icon" type="/assets/image/png" sizes="16x16" href="/assets/img/favicon.png">
		<!-- jQuery library -->
		 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
		<!-- sweetalert2 -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.33.1/sweetalert2.js"></script>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Datatable style -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">


    <!-- Icons -->
    <link rel="stylesheet" href="/assets/css/themify-icons.css">
	<!-- Tipografía -->
	<link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet">

  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<link rel="stylesheet" href="/assets/css/style.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.33.1/sweetalert2.min.css">

</head>
<body>

<div class="preloader">
	<div class="loader">
		<div class="loader__figure"></div>
		<p class="loader__label">The Library</p>
	</div>
</div>
<div id="main-wrapper">
    <!-- Topbar header -->
    <header class="topbar">
        <nav class="navbar top-navbar navbar-expand-md navbar-light">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{route('books')}}">
                    <b>
                         <img src="/assets/img/i-gde.png" alt="homepage" class="light-logo">
                    </b>
                        <span class="hidden-xs" style=""><img id="logotipo" src="/assets/img/logo-hor-gde.png" alt="Logotipo"></span>
                </a>
            </div>
            <div class="navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"> <a class="nav-link nav-toggler d-block d-md-none waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                </ul>
                <ul class="navbar-nav my-lg-0">
                    <li class="nav-item dropdown u-pro">
                        <a class="nav-link dropdown-toggle waves-effect waves-dark profile-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="hidden-md-down">¡Hola Administrador! </span>
													<img src="/assets/img/images.png" alt="user" class="">
												</a>

                    </li>
                </ul>

            </div>
	   </nav>
    </header>
    <!-- /Topbar header -->
    <!-- Menú Lateral -->
    <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar ps ps--theme_default ps--active-y" data-ps-id="2956b301-199e-ac47-8478-915e392d3a93">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav ">
                    <ul id="sidebarnav" class="in">

												<li class=""> <a class="" href="{{route('books')}}"><i class="fa fa-briefcase" aria-hidden="true"></i><span class="hide-menu">List of books</span></a>
                        </li>
												<li class=""> <a class="" href="{{route('books.create')}}"><i class="fa fa-briefcase" aria-hidden="true"></i><span class="hide-menu">Add book</span></a>
                        </li>

                    </ul>
                </nav>

            <!-- End Sidebar scroll-->
    </aside>
    <!-- /Menú Lateral -->
    <!-- Contenido -->
    <div class="page-wrapper">
			@yield('content')
    </div>
    <!-- /Contenido -->


</div>
@yield('modal')

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<!-- Latest compiled JavaScript -->

<!-- DataTable -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<!-- Bootstrap Datatable -->
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- Main JS -->
<script src="/assets/js/menu-lateral.js"></script>
<script src="/assets/js/main.js"></script>
@yield('script')
</body>

</html>